
port:
  eureka: 8001
  gateway: 8000
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dopimex_${spring.application.name}
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:${port.eureka}/eureka
